// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPG_Console_App_Game.Data;

#nullable disable

namespace RPG_Console_App_Game.Migrations
{
    [DbContext(typeof(GameDBContext))]
    [Migration("20240613210641_changedIDToInt")]
    partial class changedIDToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RPG_Console_App_Game.Data.Entities.Archer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgilityPoints")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("IntelligencePoints")
                        .HasColumnType("int");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<int>("StrengthPoints")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("TimeOfCreation")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Archers");
                });

            modelBuilder.Entity("RPG_Console_App_Game.Data.Entities.Mage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgilityPoints")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("IntelligencePoints")
                        .HasColumnType("int");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<int>("StrengthPoints")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("TimeOfCreation")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Mages");
                });

            modelBuilder.Entity("RPG_Console_App_Game.Data.Entities.Warrior", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgilityPoints")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("IntelligencePoints")
                        .HasColumnType("int");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<int>("StrengthPoints")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("TimeOfCreation")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Warriors");
                });
#pragma warning restore 612, 618
        }
    }
}
